/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 15.2 		*/
/*  Created On : 19-февр.-2022 01:12:32 				*/
/*  DBMS       : SQL Server 2012 						*/
/* ---------------------------------------------------- */

/* Drop Foreign Key Constraints */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[FK_employee_position]') AND OBJECTPROPERTY(id, N'IsForeignKey') = 1) 
ALTER TABLE [employee] DROP CONSTRAINT [FK_employee_position]
GO

/* Drop Tables */

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[employee]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [employee]
GO

IF EXISTS (SELECT 1 FROM dbo.sysobjects WHERE id = object_id(N'[position]') AND OBJECTPROPERTY(id, N'IsUserTable') = 1) 
DROP TABLE [position]
GO

/* Create Tables */

CREATE TABLE [employee]
(
	[e_id] int NOT NULL IDENTITY (1, 1),
	[e_name] varchar(50) NOT NULL,
	[e_surname] varchar(50) NOT NULL,
	[e_position_id] int NOT NULL,
	[e_birthday] date NOT NULL,
	[e_salary] money NOT NULL
)
GO

CREATE TABLE [position]
(
	[p_id] int NOT NULL IDENTITY (1, 1),
	[p_name] varchar(200) NOT NULL
)
GO

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE [employee] 
 ADD CONSTRAINT [PK_employee]
	PRIMARY KEY CLUSTERED ([e_id] ASC)
GO

CREATE NONCLUSTERED INDEX [IXFK_employee_position] 
 ON [employee] ([e_position_id] ASC)
GO

ALTER TABLE [position] 
 ADD CONSTRAINT [PK_position]
	PRIMARY KEY CLUSTERED ([p_id] ASC)
GO

CREATE UNIQUE NONCLUSTERED INDEX [UNQ_name] 
 ON [position] ([p_name] ASC)
GO

/* Create Foreign Key Constraints */

ALTER TABLE [employee] ADD CONSTRAINT [FK_employee_position]
	FOREIGN KEY ([e_position_id]) REFERENCES [position] ([p_id]) ON DELETE CASCADE ON UPDATE CASCADE
GO
